apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: emailservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: emailservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: adservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: adservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkoutservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: checkoutservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: currencyservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: currencyservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paymentservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: paymentservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: productcatalogservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: productcatalogservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recommendationservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: recommendationservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shippingservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: shippingservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cartservice-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cartservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loadgenerator-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: loadgenerator
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-cart-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis-cart